version: '3.9'

services:
  esapi:
    container_name: esapi
    image: esapi:dev
    build: 
        context: /
        dockerfile: dev.Dockerfile
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=esdb;Port=5432;Database=esdatabase;Username=testuser;Password=test123"
    depends_on:
      - esdb
  
  esdb:
    container_name: esdb
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: testuser
      POSTGRES_DB: esdatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}